import {COLORS} from '@src/constants/styles';
import {Platform, StyleSheet} from 'react-native';

/**
 * Styles which can be used in multiple places must be defined here.
 */
export const commonStyles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.WHITE,
    marginTop: Platform.select({
      ios: 14,
      android: 0,
    }),
    paddingTop: 24,
  },
  dashboardContainer: {
    paddingHorizontal: 16,
    marginTop: 14,
  },
  flex_1: {flex: 1},
  flexRow: {flexDirection: 'row'},
  flexRowReverse: {flexDirection: 'row-reverse'},
  flexWrap: {flexWrap: 'wrap'},
  flexColumn: {flexDirection: 'column'},
  flexColumnReverse: {flexDirection: 'column-reverse'},
  alignSelfStart: {alignSelf: 'flex-start'},
  alignSelfEnd: {alignSelf: 'flex-end'},
  alignSelfStretch: {alignSelf: 'stretch'},
  alignSelfCenter: {alignSelf: 'center'},
  alignItemsCenter: {alignItems: 'center'},
  alignItemsStart: {alignItems: 'flex-start'},
  alignItemsEnd: {alignItems: 'flex-end'},
  justifyContentBetween: {justifyContent: 'space-between'},
  justifyContentCenter: {justifyContent: 'center'},
  justifyContentEnd: {justifyContent: 'flex-end'},
  justifyContentStart: {justifyContent: 'flex-start'},
  justifyContentSpaceEvenly: {justifyContent: 'space-evenly'},
  justifyContentSpaceAround: {justifyContent: 'space-around'},
  absolute: {position: 'absolute'},
  center: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerContainer: {
    alignItems: 'center',
    alignContent: 'stretch',
  },

  noMargin: {marginTop: 0, marginBottom: 0, marginLeft: 0, marginRight: 0},
  noPadding: {paddingHorizontal: 0, paddingVertical: 0},
  pb_1: {paddingBottom: 1},
  pb_4: {paddingBottom: 4},
  pb_8: {paddingBottom: 8},
  pb_12: {paddingBottom: 12},
  pb_16: {paddingBottom: 16},
  pb_24: {paddingBottom: 24},
  pb_32: {paddingBottom: 32},
  pb_100: {paddingBottom: 100},
  pt_4: {paddingTop: 4},
  pt_8: {paddingTop: 8},
  pt_12: {paddingTop: 12},
  pt_16: {paddingTop: 16},
  pt_24: {paddingTop: 24},
  pt_32: {paddingTop: 32},
  pt_110: {paddingTop: 110},
  pv_1: {paddingVertical: 1},
  pv_4: {paddingVertical: 4},
  pv_8: {paddingVertical: 8},
  pv_12: {paddingVertical: 12},
  pv_16: {paddingVertical: 16},
  pv_24: {paddingVertical: 24},
  pv_32: {paddingVertical: 32},
  pv_55: {paddingVertical: 50},
  pv_60: {paddingVertical: 60},
  ph_4: {paddingHorizontal: 4},
  ph_8: {paddingHorizontal: 8},
  ph_12: {paddingHorizontal: 12},
  ph_16: {paddingHorizontal: 16},
  ph_24: {paddingHorizontal: 24},
  ph_32: {paddingHorizontal: 32},
  ph_60: {paddingHorizontal: 60},
  pr_10: {paddingRight: 10},
  pr_12: {paddingRight: 12},
  pl_10: {paddingLeft: 10},
  mb_0: {marginBottom: 0},

  mb_4: {marginBottom: 4},
  mb_8: {marginBottom: 8},
  mb_12: {marginBottom: 12},
  mb_16: {marginBottom: 16},
  mb_20: {marginBottom: 20},
  mb_24: {marginBottom: 24},
  mb_32: {marginBottom: 32},
  mt_2: {marginTop: 2},
  mt_4: {marginTop: 4},
  mt_8: {marginTop: 8},
  mt_12: {marginTop: 12},
  mt_16: {marginTop: 16},
  mt_24: {marginTop: 24},
  mt_32: {marginTop: 32},
  mt_36: {marginTop: 36},
  mt_60: {marginTop: 60},
  mt_40: {marginTop: 40},
  mt_70: {marginTop: 70},
  mt_100: {marginTop: 100},
  mt_110: {marginTop: 110},
  mt_130: {marginTop: 130},
  mt_150: {marginTop: 150},
  mt_200: {marginTop: 200},
  mt_300: {marginTop: 300},
  ml_2: {marginLeft: 2},
  ml_4: {marginLeft: 4},
  ml_6: {marginLeft: 6},
  ml_8: {marginLeft: 8},
  ml_12: {marginLeft: 12},
  ml_16: {marginLeft: 16},
  ml_24: {marginLeft: 24},
  ml_32: {marginLeft: 32},
  ml_125: {marginLeft: 125},
  ml_150: {marginLeft: 150},
  ml_155: {marginLeft: 155},
  ml_180: {marginLeft: 180},
  ml_110: {marginLeft: 110},
  mr_4: {marginRight: 4},
  mr_8: {marginRight: 8},
  mr_6: {marginRight: 6},
  mr_12: {marginRight: 12},
  mr_16: {marginRight: 16},
  mr_24: {marginRight: 24},
  mr_32: {marginRight: 32},
  mv_4: {marginVertical: 4},
  mv_8: {marginVertical: 8},
  mv_12: {marginVertical: 12},
  mv_16: {marginVertical: 16},
  mv_24: {marginVertical: 24},
  mv_32: {marginVertical: 32},
  mh_4: {marginHorizontal: 4},
  mh_8: {marginHorizontal: 8},
  mh_12: {marginHorizontal: 12},
  mh_16: {marginHorizontal: 16},
  mh_24: {marginHorizontal: 24},
  mh_32: {marginHorizontal: 32},

  txtCenter: {
    textAlign: 'center',
  },

  rotate_10: {transform: [{rotate: '10deg'}]},
  rotate_90: {transform: [{rotate: '90deg'}]},
  rotate_180: {transform: [{rotate: '180deg'}]},
  rotate_170: {transform: [{rotate: '170deg'}]},
  rotate_225: {transform: [{rotate: '225deg'}]},
  rotate_315: {transform: [{rotate: '315deg'}]},

  rotate_270: {transform: [{rotate: '270deg'}]},

  labelWeightBold: {fontWeight: 'bold'},
  labelWeight400: {fontWeight: '400'},
  labelWeight500: {fontWeight: '500'},
  labelWeight600: {fontWeight: '600'},
  labelWeight700: {fontWeight: '700'},
  labelWeight800: {fontWeight: '800'},

  fs_12: {fontSize: 12},
  fs_8: {fontSize: 8},
  fs_10: {fontSize: 10},
  fs_16: {fontSize: 16},
  fs_18: {fontSize: 18},
  fs_14: {fontSize: 14},
  fs_20: {fontSize: 20},
  fs_24: {fontSize: 24},
  fs_26: {fontSize: 26},
  fs_28: {fontSize: 28},
  fs_40: {fontSize: 40},

  fw_500: {fontWeight: '500'},
  fw_700: {fontWeight: '700'},

  bgWhite: {backgroundColor: COLORS.WHITE},
  whiteColor: {color: COLORS.WHITE},
  blackColor: {
    color: COLORS.BLACK,
  },
});
